name: Update GitHub Activity

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  update_activity:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.name "Theo-Dayton"
          git config --global user.email "tdaytonmohl@gmail.com"

      - name: Update daily log
        run: |
          echo "Last update: $(date)" > activity.log
          git add activity.log
          git commit -m "Daily update: $(date)" || echo "No changes to commit"
          git push
